# ---------------------------------------------------------------
# Configuration File
# Docs: https://jekyllrb.com/docs/configuration/
# ---------------------------------------------------------------

# Site
title: Erofive
subtitle: Lovelive!
description: Website of Our Erolive.
author: Erolovers'
language: zh-Hans
date_format: '%Y-%m-%d'

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com' and baseurl as '/child'
url:
baseurl:
permalink: pretty

# Pagination
paginate: 7
#paginate_path: "/page:num/"
archive:
  paginate: 10
  #paginate_path: "/page:num/"
#category:
  #paginate: 10
  #paginate_path: "/page:num/"
#tag:
  #paginate: 10
  #paginate_path: "/page:num/"

# Handling Reading
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock", "README_en.md", "vendor"]

# Highlighter
highlighter: rouge
highlight:
  line_number: true

# Markdown
markdown: kramdown
kramdown:
    input: GFM

# Default Attributes
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-paginate

# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

favicon: /assets/images/favicon.ico

# Set default keywords (Use a comma to separate)
keywords: "Jekyll, NexT, PCR, BCR, Guild, Erolive, Judui"

# Specify the date when the site was setup
since: 2020

# icon between year and author @Footer
authoricon: heart

# @Footer `powered-by` and `theme-info` copyright
copyright: true

# ---------------------------------------------------------------
# SEO Settings
# ---------------------------------------------------------------

# If true, will add site-subtitle to index page, added in jekyll config.
# subtitle: Subtitle
index_with_subtitle: false

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

# When running the site in a subdirectory (e.g. domain.tld/blog), remove the leading slash (/archives -> archives)
menu:
  home: /
  about: /about/
  categories: /categories/
  archives: /archives/
  tags: /tags/
  
# Enable/Disable menu icons.
menu_icons:
  enable: true
  #KeyMapsToMenuItemKey: NameOfTheIconFromFontAwesome
  home: code
  about: quote-right
  categories: th
  # schedule: calendar
  tags: tags
  archives: archive

# ---------------------------------------------------------------
# Scheme Settings
# ---------------------------------------------------------------

# Schemes
scheme: Pisces

# ---------------------------------------------------------------
# Font Settings
# - Find fonts on Google Fonts (https://www.google.com/fonts)
# - All fonts set here will have the following styles:
#     light, light italic, normal, normal italic, bold, bold italic
# - Be aware that setting too much fonts will cause site running slowly
# - Introduce in 5.0.1
# ---------------------------------------------------------------
font:
  enable: true

  # Uri of fonts host. E.g. //fonts.googleapis.com (Default)
  host:

  # Global font settings used on <body> element.
  global:
    # external: true will load this font family from host.
    external: true
    family: Lato

  # Font settings for Headlines (h1, h2, h3, h4, h5, h6)
  # Fallback to `global` font settings.
  headings:
    external: true
    family:

  # Font settings for posts
  # Fallback to `global` font settings.
  posts:
    external: true
    family:

  # Font settings for Logo
  # Fallback to `global` font settings.
  # The `size` option use `px` as unit
  logo:
    external: true
    family:
    size:

  # Font settings for <code> and code blocks.
  codes:
    external: true
    family:
    size:

# ---------------------------------------------------------------
# Sidebar Settings
# ---------------------------------------------------------------

# Table Of Contents in the Sidebar
toc:
  enable: true

  # Automatically add list number to toc.
  number: true

  # If true, all words will placed on next lines if header width longer then sidebar width.
  wrap: false

sidebar:
  # Sidebar Position, available value: left | right
  position: right

  # Sidebar Display, available value:
  #  - post    expand on posts automatically. Default.
  #  - always  expand for all pages automatically
  #  - hide    expand only when click on the sidebar toggle icon.
  #  - remove  Totally remove sidebar including sidebar toggle.
  display: post

  # Sidebar offset from top menubar in pixels.
  offset: 12
  offset_float: 0

  # Back to top in sidebar
  b2t: true

  # Scroll percent label in b2t button
  scrollpercent: false

# ---------------------------------------------------------------
# Post Settings
# ---------------------------------------------------------------

# Automatically scroll page to section which is under <!-- more --> mark.
scroll_to_more: true

# Automatically saving scroll position on each post/page in cookies.
save_scroll: false

# Automatically excerpt description in homepage as preamble text.
excerpt_description: true

# Post meta display settings
post_meta:
  item_text: true
  created_at: true
  updated_at: false
  categories: true

# Post wordcount display settings
post_wordcount:
  item_text: true
  wordcount: false
  min2read: false
  separated_meta: true

# ---------------------------------------------------------------
# Misc Theme Settings
# ---------------------------------------------------------------

# Custom Logo.
# !!Only available for Default Scheme currently.
# Options:
#   enabled: [true/false] - Replace with specific image
#   image: url-of-image   - Images's url
custom_logo:
  enabled: false
  image:

# Code Highlight theme
# Available value:
#    normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: normal



#! ---------------------------------------------------------------
#! DO NOT EDIT THE FOLLOWING SETTINGS UNLESS U KNOW WHAT U R DOING
#! ---------------------------------------------------------------

# Motion
use_motion: false

# Fancybox
fancybox: true

# Progress bar in the top during page loading.
pace: false
# Themes list:
##  pace-theme-big-counter
## pace-theme-bounce
## pace-theme-barber-shop
## pace-theme-center-atom
## pace-theme-center-circle
## pace-theme-center-radar
## pace-theme-center-simple
## pace-theme-corner-indicator
## pace-theme-fill-left
## pace-theme-flash
## pace-theme-loading-bar
## pace-theme-mac-osx
## pace-theme-minimal
pace_theme: pace-theme-minimal

# Script Vendors.
## Set a CDN address for the vendor you want to customize.
vendors:
  # Internal path prefix. Please do not edit it.
  _internal: assets/lib

  # Version: 2.1.3
  jquery: //cdn.bootcdn.net/ajax/libs/jquery/2.1.3/jquery.min.js

  # Internal version: 2.1.5
  # See: http://fancyapps.com/fancybox/
  fancybox:
  fancybox_css:

  # Version: 1.0.6
  fastclick: //cdn.bootcdn.net/ajax/libs/fastclick/1.0.6/fastclick.min.js

  # Version: 1.9.7
  lazyload: //cdn.bootcdn.net/ajax/libs/jquery_lazyload/1.9.7/jquery.lazyload.min.js

  # Version: 1.2.1
  velocity: //cdn.bootcdn.net/ajax/libs/velocity/1.2.1/velocity.min.js
  velocity_ui: //cdn.bootcdn.net/ajax/libs/velocity/1.2.1/velocity.ui.min.js

  # Version: 0.7.9
  ua_parser: //cdn.bootcdn.net/ajax/libs/UAParser.js/0.7.9/ua-parser.min.js

  # Version: 4.6.2
  fontawesome: //cdn.bootcdn.net/ajax/libs/font-awesome/4.6.2/css/font-awesome.min.css

  # Internal version: 1.0.2
  # See: https://github.com/HubSpot/pace
  pace:
  pace_css:

  # Version: 1.0.1
  canvas_nest: //cdn.bootcdn.net/ajax/libs/canvas-nest.js/1.0.1/canvas-nest.min.js


# Assets
css: assets/css
js: assets/js
images: assets/images

# Theme version
version: 5.1.1
